server:
  port: 8080
  servlet:
    context-path: /data-analyzer
    
spring.jpa:
  database: POSTGRESQL
  hibernate:
   ddl-auto: create-drop
  show-sql: true

spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres
  
app-config:
  env: Running with local resource
  